import {test,expect} from '@playwright/test';

const CASES=[
  {"id":"01A","municipality":"Leiden","code":"0546","address":"Breestraat 1-A, 2311 CG Leiden","postcode":"2311CG","number":1,"addition":"A","street":"Breestraat","bagId":"0546200000009710","bagUses":["woonfunctie"],"neighborhood":"","goal":"rooms","patterns":["verhuurvergunning","omzettingsvergunning","25%"],"outcome":"conditional","answers":["yes"]},
  {"id":"01B","municipality":"Leiden","code":"0546","address":"Robijnhof 2, 2332 KJ Leiden","postcode":"2332KJ","number":2,"addition":"","street":"Robijnhof","bagId":"0546200000076139","bagUses":["woonfunctie"],"neighborhood":"","goal":"rooms","patterns":["omzettingsvergunning"],"outcome":"no","answers":["yes"]},
  {"id":"02A","municipality":"Den Haag","code":"0518","address":"Frederikstraat 5 A, Den Haag","postcode":"2514LA","number":5,"addition":"A","street":"Frederikstraat","bagId":"0518010000000001","bagUses":["woonfunctie"],"neighborhood":"","goal":"rent","patterns":["opkoopbescherming","470.000"],"outcome":"conditional","answers":["yes","yes"]},
  {"id":"02B","municipality":"Den Haag","code":"0518","address":"Frederikstraat 5 A, Den Haag","postcode":"2514LA","number":5,"addition":"A","street":"Frederikstraat","bagId":"0518010000000001","bagUses":["woonfunctie"],"neighborhood":"","goal":"rent","patterns":["opkoopbescherming"],"outcome":"no","answers":["yes","no"]},
  {"id":"03A","municipality":"Emmen","code":"0114","address":"Mantingerbrink 3, 7812 MA Emmen","postcode":"7812MA","number":3,"addition":"","street":"Mantingerbrink","bagId":"0114010000000001","bagUses":["woonfunctie"],"neighborhood":"Bargeres","goal":"rent","patterns":["opkoopbescherming","250.000"],"outcome":"conditional","answers":["yes","yes"]},
  {"id":"03B","municipality":"Emmen","code":"0114","address":"Spoorstraat 5, 7811 GB Emmen","postcode":"7811GB","number":5,"addition":"","street":"Spoorstraat","bagId":"0114200000322191","bagUses":["woonfunctie"],"neighborhood":"Emmen-Centrum","goal":"rent","patterns":["opkoopbescherming"],"outcome":"no","answers":["yes"]},
  {"id":"04A","municipality":"Amsterdam","code":"0363","address":"Ferdinand Bolstraat 100-3, 1072 LN Amsterdam","postcode":"1072LN","number":100,"addition":"3","street":"Ferdinand Bolstraat","bagId":"0363200000097883","bagUses":["woonfunctie"],"neighborhood":"Oude Pijp","goal":"holiday","patterns":["vakantieverhuur","15"],"outcome":"conditional","answers":["yes","yes","yes"]},
  {"id":"04B","municipality":"Amsterdam","code":"0363","address":"Nieuwersluishof 3, 1106 PK Amsterdam","postcode":"1106PK","number":3,"addition":"","street":"Nieuwersluishof","bagId":"0363200000354022","bagUses":["woonfunctie"],"neighborhood":"Holendrecht-West","goal":"holiday","patterns":["vakantieverhuur","30"],"outcome":"conditional","answers":["yes","yes","yes"]},
  {"id":"05A","municipality":"Rotterdam","code":"0599","address":"Stadhoudersplein 1 C, Rotterdam","postcode":"3039EL","number":1,"addition":"C","street":"Stadhoudersplein","bagId":"0599200000464291","bagUses":["woonfunctie"],"neighborhood":"Blijdorp","goal":"rooms","patterns":["kamerverhuur","student"],"outcome":"conditional","answers":["yes","yes"]},
  {"id":"06A","municipality":"Utrecht","code":"0344","address":"Lelimanstraat 3, 3555 CA Utrecht","postcode":"3555CA","number":3,"addition":"","street":"Lelimanstraat","bagId":"0344200000068280","bagUses":["woonfunctie"],"neighborhood":"","goal":"split","patterns":["splits|woningvorming","omgevings"],"outcome":"conditional","answers":["yes"]},
  {"id":"07A","municipality":"Eindhoven","code":"0772","address":"Edisonstraat 144-G, 5621 HT Eindhoven","postcode":"5621HT","number":144,"addition":"G","street":"Edisonstraat","bagId":"0772010001060471","bagUses":["woonfunctie"],"neighborhood":"Woensel-West","goal":"rooms","patterns":["kamer|woningsplits","op slot|op-slot|woensel"],"outcome":"no","answers":["yes"]},
  {"id":"08A","municipality":"Groningen","code":"0014","address":"Korreweg 2-13, 9715 AA Groningen","postcode":"9715AA","number":2,"addition":"13","street":"Korreweg","bagId":"0014200010820138","bagUses":["woonfunctie"],"neighborhood":"","goal":"rooms","patterns":["omzettingsvergunning"],"outcome":"conditional","answers":["yes"]},
  {"id":"08B","municipality":"Groningen","code":"0014","address":"Korreweg 2-13, 9715 AA Groningen","postcode":"9715AA","number":2,"addition":"13","street":"Korreweg","bagId":"0014200010820138","bagUses":["woonfunctie"],"neighborhood":"","goal":"rooms","patterns":["omzettingsvergunning","brandveilig"],"outcome":"conditional","answers":["yes","yes"]},
  {"id":"09A","municipality":"Tilburg","code":"0855","address":"Pastoor Smitsstraat 5, Tilburg","postcode":"5014RH","number":5,"addition":"","street":"Pastoor Smitsstraat","bagId":"0855200000092564","bagUses":["woonfunctie"],"neighborhood":"","goal":"rooms","patterns":["omzettingsvergunning|kamerverhuur"],"outcome":"no","answers":["no"]},
  {"id":"09B","municipality":"Tilburg","code":"0855","address":"Pastoor Smitsstraat 5, Tilburg","postcode":"5014RH","number":5,"addition":"","street":"Pastoor Smitsstraat","bagId":"0855200000092564","bagUses":["woonfunctie"],"neighborhood":"","goal":"rooms","patterns":["omzettingsvergunning"],"outcome":"conditional","answers":["yes"]},
  {"id":"10A","municipality":"Breda","code":"0758","address":"Kolfbaanstraat 1 C, Breda","postcode":"4814CJ","number":1,"addition":"C","street":"Kolfbaanstraat","bagId":"0758200000001830","bagUses":["woonfunctie"],"neighborhood":"","goal":"rent","patterns":["opkoopbescherming","470.000"],"outcome":"conditional","answers":["yes","yes"]},
  {"id":"10B","municipality":"Breda","code":"0758","address":"Kolfbaanstraat 1 C, Breda","postcode":"4814CJ","number":1,"addition":"C","street":"Kolfbaanstraat","bagId":"0758200000001830","bagUses":["woonfunctie"],"neighborhood":"","goal":"rent","patterns":["opkoopbescherming"],"outcome":"no","answers":["yes","no"]},
  {"id":"11A","municipality":"Nijmegen","code":"0268","address":"Augustijnenstraat 51, 6511 KE Nijmegen","postcode":"6511KE","number":51,"addition":"","street":"Augustijnenstraat","bagId":"0268200000000415","bagUses":["woonfunctie"],"neighborhood":"","goal":"rooms","patterns":["kamer|omzet"],"outcome":"no","answers":["no"]},
  {"id":"11B","municipality":"Nijmegen","code":"0268","address":"Augustijnenstraat 51, 6511 KE Nijmegen","postcode":"6511KE","number":51,"addition":"","street":"Augustijnenstraat","bagId":"0268200000000415","bagUses":["woonfunctie"],"neighborhood":"","goal":"rooms","patterns":["kamer|omzet","278.000|woz"],"outcome":"no","answers":["yes","yes"]},
  {"id":"11C","municipality":"Nijmegen","code":"0268","address":"Augustijnenstraat 51, 6511 KE Nijmegen","postcode":"6511KE","number":51,"addition":"","street":"Augustijnenstraat","bagId":"0268200000000415","bagUses":["woonfunctie"],"neighborhood":"","goal":"rooms","patterns":["omgevingsvergunning","omzettingsvergunning"],"outcome":"conditional","answers":["yes","yes"]},
  {"id":"11D","municipality":"Nijmegen","code":"0268","address":"Augustijnenstraat 51, 6511 KE Nijmegen","postcode":"6511KE","number":51,"addition":"","street":"Augustijnenstraat","bagId":"0268200000000415","bagUses":["woonfunctie"],"neighborhood":"","goal":"rooms","patterns":["omgevingsvergunning"],"outcome":"conditional","answers":["yes","yes"]},
  {"id":"11E","municipality":"Nijmegen","code":"0268","address":"Augustijnenstraat 51, 6511 KE Nijmegen","postcode":"6511KE","number":51,"addition":"","street":"Augustijnenstraat","bagId":"0268200000000415","bagUses":["woonfunctie"],"neighborhood":"","goal":"rooms","patterns":["brandveilig"],"outcome":"conditional","answers":["yes","yes","yes"]},
  {"id":"12A","municipality":"Arnhem","code":"0202","address":"Hoflaan 4, 6824 BP Arnhem","postcode":"6824BP","number":4,"addition":"","street":"Hoflaan","bagId":"0202200000281411","bagUses":["woonfunctie"],"neighborhood":"","goal":"split","patterns":["splits|woningvorming","parkeren|parkeer"],"outcome":"conditional","answers":["yes"]},
  {"id":"12B","municipality":"Arnhem","code":"0202","address":"Hoflaan 4, 6824 BP Arnhem","postcode":"6824BP","number":4,"addition":"","street":"Hoflaan","bagId":"0202200000281411","bagUses":["woonfunctie"],"neighborhood":"","goal":"rooms","patterns":["omgevingsvergunning","brandveilig"],"outcome":"conditional","answers":["yes","yes"]},
  {"id":"13A","municipality":"Haarlem","code":"0392","address":"Korte Begijnestraat 12, 2011 HC Haarlem","postcode":"2011HC","number":12,"addition":"","street":"Korte Begijnestraat","bagId":"0392200000033231","bagUses":["woonfunctie"],"neighborhood":"","goal":"holiday","patterns":["vakantieverhuur","30"],"outcome":"conditional","answers":["yes","yes"]},
  {"id":"13B","municipality":"Haarlem","code":"0392","address":"Korte Begijnestraat 12, 2011 HC Haarlem","postcode":"2011HC","number":12,"addition":"","street":"Korte Begijnestraat","bagId":"0392200000033231","bagUses":["woonfunctie"],"neighborhood":"","goal":"holiday","patterns":["vakantieverhuur","30"],"outcome":"no","answers":["yes","no"]},
  {"id":"13C","municipality":"Haarlem","code":"0392","address":"Korte Begijnestraat 12, 2011 HC Haarlem","postcode":"2011HC","number":12,"addition":"","street":"Korte Begijnestraat","bagId":"0392200000033231","bagUses":["woonfunctie"],"neighborhood":"","goal":"holiday","patterns":["vakantieverhuur|hoofdverblijf"],"outcome":"no","answers":["no"]},
  {"id":"14A","municipality":"Delft","code":"0503","address":"Aart van der Leeuwlaan 13, 2624 PK Delft","postcode":"2624PK","number":13,"addition":"","street":"Aart van der Leeuwlaan","bagId":"0503200000001119","bagUses":["woonfunctie"],"neighborhood":"","goal":"rooms","patterns":["omzettingsvergunning","verhuurvergunning|brandveilig"],"outcome":"conditional","answers":["yes","yes"]},
  {"id":"15A","municipality":"Maastricht","code":"0935","address":"Gebroeders van Limburgstraat 9, 6219 AD Maastricht","postcode":"6219AD","number":9,"addition":"","street":"Gebroeders van Limburgstraat","bagId":"0935200000096178","bagUses":["woonfunctie"],"neighborhood":"","goal":"rooms","patterns":["140","kamer|omzet"],"outcome":"no","answers":["no"]},
  {"id":"15B","municipality":"Maastricht","code":"0935","address":"Frankenstraat 160, 6224 GT Maastricht","postcode":"6224GT","number":160,"addition":"","street":"Frankenstraat","bagId":"0935010000051064","bagUses":["woonfunctie"],"neighborhood":"","goal":"split","patterns":["140","splits"],"outcome":"conditional","answers":["yes","yes"]},
  {"id":"16A","municipality":"Enschede","code":"0153","address":"Margaretha Roosenboomlaan 1, 7545 RX Enschede","postcode":"7545RX","number":1,"addition":"","street":"Margaretha Roosenboomlaan","bagId":"0153200000327186","bagUses":["woonfunctie"],"neighborhood":"Boswinkel-Stadsveld","goal":"rent","patterns":["opkoopbescherming","365.000"],"outcome":"no","answers":["yes","no"]},
  {"id":"16B","municipality":"Enschede","code":"0153","address":"Margaretha Roosenboomlaan 1, 7545 RX Enschede","postcode":"7545RX","number":1,"addition":"","street":"Margaretha Roosenboomlaan","bagId":"0153200000327186","bagUses":["woonfunctie"],"neighborhood":"Boswinkel-Stadsveld","goal":"rent","patterns":["opkoopbescherming","365.000"],"outcome":"conditional","answers":["yes","yes"]},
  {"id":"17A","municipality":"Almere","code":"0034","address":"Neonweg 6, 1362 AE Almere","postcode":"1362AE","number":6,"addition":"","street":"Neonweg","bagId":"0034200000093334","bagUses":["industriefunctie","kantoorfunctie"],"neighborhood":"","goal":"tohome","patterns":["bedrijf|kantoor","wonen|woning"],"outcome":"no","answers":["yes"]},
  {"id":"18A","municipality":"Apeldoorn","code":"0200","address":"Loolaan 49, 7314 AE Apeldoorn","postcode":"7314AE","number":49,"addition":"","street":"Loolaan","bagId":"0200010000138321","bagUses":["woonfunctie"],"neighborhood":"","goal":"renovate","patterns":["monument|erfgoed","omgevingsvergunning"],"outcome":"conditional","answers":["yes"]},
  {"id":"19A","municipality":"Gouda","code":"0513","address":"Korte Groenendaal 11, 2801 JP Gouda","postcode":"2801JP","number":11,"addition":"","street":"Korte Groenendaal","bagId":"0513200000015959","bagUses":["winkelfunctie"],"neighborhood":"","goal":"tohome","patterns":["wonen","kernwinkel|begane grond|omgevingsplan"],"outcome":"no","answers":["yes"]},
  {"id":"19B","municipality":"Gouda","code":"0513","address":"Korte Groenendaal 11, 2801 JP Gouda","postcode":"2801JP","number":11,"addition":"","street":"Korte Groenendaal","bagId":"0513200000015959","bagUses":["winkelfunctie"],"neighborhood":"","goal":"tohome","patterns":["wonen","winkel"],"outcome":"conditional","answers":["yes"]},
  {"id":"20A","municipality":"Dordrecht","code":"0505","address":"Bagijnhof 4, 3311 KE Dordrecht","postcode":"3311KE","number":4,"addition":"","street":"Bagijnhof","bagId":"0505200000003704","bagUses":["winkelfunctie"],"neighborhood":"","goal":"split","patterns":["woningvorming","omgevingsvergunning"],"outcome":"conditional","answers":["yes"]},
  {"id":"21A","municipality":"Leeuwarden","code":"0080","address":"Orionweg 1, 8938 AG Leeuwarden","postcode":"8938AG","number":1,"addition":"","street":"Orionweg","bagId":"0080010000000001","bagUses":["kantoorfunctie"],"neighborhood":"","goal":"tohome","patterns":["kantoor|niet-woon","woning|wonen"],"outcome":"no","answers":["yes"]},
  {"id":"21B","municipality":"Leeuwarden","code":"0080","address":"Groningerstraatweg 1, 8922 AP Leeuwarden","postcode":"8922AP","number":1,"addition":"","street":"Groningerstraatweg","bagId":"0080010000432044","bagUses":["woonfunctie"],"neighborhood":"","goal":"rooms","patterns":["kamer|hospita"],"outcome":"no","answers":["no"]},
  {"id":"21C","municipality":"Leeuwarden","code":"0080","address":"Groningerstraatweg 1, 8922 AP Leeuwarden","postcode":"8922AP","number":1,"addition":"","street":"Groningerstraatweg","bagId":"0080010000432044","bagUses":["woonfunctie"],"neighborhood":"","goal":"rooms","patterns":["kamer","3"],"outcome":"no","answers":["yes"]},
  {"id":"22A","municipality":"Deventer","code":"0150","address":"Bergsingel 51, 7411 CN Deventer","postcode":"7411CN","number":51,"addition":"","street":"Bergsingel","bagId":"0150200000008214","bagUses":["woonfunctie"],"neighborhood":"","goal":"rooms","patterns":["omzettingsvergunning","470.000|woz"],"outcome":"conditional","answers":["yes","yes"]},
  {"id":"23A","municipality":"Bodegraven-Reeuwijk","code":"1901","address":"De Steupel 4, Reeuwijk","postcode":"2811NP","number":4,"addition":"","street":"De Steupel","bagId":"1901010000000001","bagUses":["woonfunctie"],"neighborhood":"","goal":"rent","patterns":["opkoopbescherming"],"outcome":"conditional","answers":["yes","yes"]},
  {"id":"23B","municipality":"Bodegraven-Reeuwijk","code":"1901","address":"De Steupel 4, Reeuwijk","postcode":"2811NP","number":4,"addition":"","street":"De Steupel","bagId":"1901010000000001","bagUses":["woonfunctie"],"neighborhood":"","goal":"rent","patterns":["opkoopbescherming"],"outcome":"no","answers":["no"]},
  {"id":"24A","municipality":"Doesburg","code":"0221","address":"Baer 5, 6982 JB Doesburg","postcode":"6982JB","number":5,"addition":"","street":"Baer","bagId":"0221010000334225","bagUses":["woonfunctie"],"neighborhood":"","goal":"tohome","patterns":["omgevingsplan|functie|gebruik"],"outcome":"precision","answers":["yes"]},
  {"id":"25A","municipality":"Dantumadiel","code":"1891","address":"Mûnewei 2, 9104 CX Damwâld","postcode":"9104CX","number":2,"addition":"","street":"Mûnewei","bagId":"1891200011149585","bagUses":["woonfunctie"],"neighborhood":"","goal":"rent","patterns":[],"outcome":"none","answers":["yes"]},
  {"id":"25B","municipality":"Dantumadiel","code":"1891","address":"Mûnewei 2, 9104 CX Damwâld","postcode":"9104CX","number":2,"addition":"","street":"Mûnewei","bagId":"1891200011149585","bagUses":["woonfunctie"],"neighborhood":"","goal":"rent","patterns":["leegstand|tijdelijke verhuur|tijdelijk"],"outcome":"conditional","answers":["yes"]}
];

const GOAL_LABELS={"rent":"Gehele woning verhuren","rooms":"Kamers verhuren / woning delen","split":"Woning splitsen","holiday":"Vakantieverhuur / Airbnb","tohome":"Pand naar woning veranderen","renovate":"Verbouwen"};

function pdokDoc(c){return {postcode:c.postcode,huisnummer:c.number,huisnummertoevoeging:c.addition||undefined,straatnaam:c.street,weergavenaam:c.address,gemeentecode:c.code,gemeentenaam:c.municipality,buurtcode:c.neighborhood?`TEST-${c.code}-${c.neighborhood}`:undefined,buurtnaam:c.neighborhood||undefined,wijkcode:undefined,wijknaam:c.neighborhood||undefined,adresseerbaarobject_id:c.bagId,centroide_ll:'POINT(5.0000 52.0000)',gebruiksdoel:c.bagUses};}
async function mockPdok(page,c){await page.route('https://api.pdok.nl/**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({response:{numFound:1,docs:[pdokDoc(c)]}})}));}
async function openCase(page,c){await mockPdok(page,c);await page.goto('/');await page.locator('#postcode').fill(c.postcode);await page.locator('#number').fill(String(c.number));if(c.addition)await page.locator('#addition').fill(c.addition);await page.getByRole('button',{name:'Controleer adres'}).click();await expect(page.locator('#address')).toContainText(c.municipality);const label=GOAL_LABELS[c.goal];await page.getByRole('button',{name:new RegExp(label.replace('/','\\/'),'i')}).click();}
async function answerVisibleQuestions(page,c){let i=0;for(let guard=0;guard<12;guard++){const selects=page.locator('.guided-questions select:visible');const count=await selects.count();if(!count)break;const select=selects.first();const value=c.answers[Math.min(i,c.answers.length-1)]||'yes';await select.selectOption(value);i++;await page.waitForTimeout(20);}}
function regex(s){return new RegExp(s,'i')}

test.describe('Golden matrix — 46 praktijkpaden',()=>{
  for(const c of CASES){
    test(`${c.id} · ${c.municipality} · ${c.goal}`,async({page})=>{
      const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
      await openCase(page,c);await answerVisibleQuestions(page,c);
      const results=page.locator('.guided-results');const pageText=page.locator('#rules');
      if(c.outcome==='none'){
        await expect(pageText).toContainText(/Nog geen automatische conclusie|geen complete machineleesbare beslisroute/i);
        await expect(results.locator('.guided-card')).toHaveCount(0);
      }else if(c.outcome==='precision'){
        for(const p of c.patterns)await expect(pageText).toContainText(regex(p));
        await expect(pageText).not.toContainText(/opkoopbescherming|verhuurvergunning.*opkoop|kamerverhuurvergunning/i);
      }else{
        await expect(results).toBeVisible();
        for(const p of c.patterns)await expect(pageText).toContainText(regex(p));
        const outcomeClass=c.outcome==='no'?'.outcome-no':'.outcome-conditional';
        await expect(results.locator(outcomeClass).first()).toBeVisible();
      }
      expect(errors,`console/page errors in ${c.id}`).toEqual([]);
    });
  }
});