import assert from 'node:assert/strict';
import fs from 'node:fs';
import {evaluateRule,STATES} from '../assets/applicability.js';
const read=p=>JSON.parse(fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8'));
const regs=read('data/regulations.json').records||[],municipalities=read('data/municipalities-2026.json').municipalities||[],confidence=read('data/source-confidence-municipalities.json'),locationRules=read('data/location-rules.json').records||[];
let passed=0,failed=0,warnings=0;function test(n,f){try{f();console.log(`PASS  ${n}`);passed++}catch(e){console.error(`FAIL  ${n}\n      ${e.message}`);failed++}}function warn(n,m){console.warn(`WARN  ${n}: ${m}`);warnings++}const context=(code,name='Testgemeente',postcode='1234AB')=>({municipality:{code,name},address:{postcode,houseNumber:1,street:'Teststraat'},location:{},property:{}});
console.log('\n=== Woningencheck regressietest ===');
test('342 gemeenten aanwezig',()=>assert.equal(municipalities.length,342));test('gemeentecodes zijn uniek',()=>assert.equal(new Set(municipalities.map(x=>x.code)).size,342));test('landelijke audit dekt 342 gemeenten',()=>assert.equal(Object.keys(confidence.municipalities||{}).length,342));test('landelijke audit representeert 799 bronrecords',()=>assert.equal(Number(confidence.records),799));test('alle auditgemeenten hebben minimaal één bron',()=>assert.equal(Object.values(confidence.municipalities||{}).filter(x=>!x.n).length,0));test('alle beslisregels hebben gemeente en titel',()=>assert.equal(regs.filter(r=>!r.id||!r.municipalityCode||!r.title).length,0));test('alle beslisregel-IDs zijn uniek',()=>assert.equal(new Set(regs.map(r=>r.id)).size,regs.length));test('officiële regelgevingslinks gebruiken https',()=>assert.equal(regs.filter(r=>r.officialRegulationUrl&&!r.officialRegulationUrl.startsWith('https://')).length,0));test('officiële informatielinks gebruiken https',()=>assert.equal(regs.filter(r=>r.officialInformationUrl&&!r.officialInformationUrl.startsWith('https://')).length,0));test('aanvraaglinks gebruiken https',()=>assert.equal(regs.filter(r=>r.officialApplicationUrl&&!r.officialApplicationUrl.startsWith('https://')).length,0));
const leiden=regs.find(r=>r.municipalityCode==='GM0546'&&String(r.title).toLowerCase().includes('opkoop'));test('Leiden opkoopbescherming zit in de beslisdatabase',()=>assert.ok(leiden));if(leiden?.applicability){const users=leiden.applicability.conditions.filter(c=>c.source==='user-input');test('Leiden heeft meerdere gebruikersvoorwaarden',()=>assert.ok(users.length>=2));test('beslisboom toont één vraag tegelijk',()=>{const e=evaluateRule(leiden,context('GM0546','Leiden','2315SW'),{});if(e.state===STATES.QUESTIONS)assert.equal(e.questions.length,1);else assert.ok([STATES.INSUFFICIENT,STATES.REVIEW].includes(e.state))});if(users[0])test('Nee op eerste Leiden-vraag stopt vervolgvragen',()=>{const e=evaluateRule(leiden,context('GM0546','Leiden','2315SW'),{[users[0].id]:'no'});assert.equal(e.state,STATES.NOT_APPLICABLE);assert.equal(e.questions.length,0)});if(users[1])test('Nee op tweede Leiden-vraag stopt vervolgvragen',()=>{const a={[users[0].id]:String(users[0].value??'yes'),[users[1].id]:'no'},e=evaluateRule(leiden,context('GM0546','Leiden','2315SW'),a);assert.equal(e.state,STATES.NOT_APPLICABLE);assert.equal(e.questions.length,0)})}
test('Leiden 2315SW heeft officiële locatie-override',()=>{const x=locationRules.find(x=>x.municipalityCode==='GM0546'&&x.postcode==='2315SW');assert.ok(x);assert.equal(x.rules?.conversionPermit,true)});
const goudaRule={municipalityCode:'GM0513',applicability:{conclusiveWhenMatched:false,matchMessage:'Omgevingsvergunningroute verder controleren.',conditions:[{id:'gouda-hospita-exception',source:'user-input',operator:'equals',value:'no'}]}};
test('Gouda hospita ja sluit vergunningregel uit',()=>assert.equal(evaluateRule(goudaRule,context('GM0513','Gouda'),{'gouda-hospita-exception':'yes'}).state,STATES.NOT_APPLICABLE));
test('Gouda hospita nee houdt vergunningroute open',()=>assert.equal(evaluateRule(goudaRule,context('GM0513','Gouda'),{'gouda-hospita-exception':'no'}).state,STATES.POTENTIAL));
const candidates=regs.filter(r=>r.applicability?.conditions?.some(c=>c.source==='user-input'));test('alle huidige interactieve beslisregels zijn opgenomen',()=>assert.ok(candidates.length>=2));candidates.forEach((r,i)=>test(`interactieve regel ${i+1} · ${r.municipalityName||r.municipalityCode} · ${r.title}`,()=>{const e0=evaluateRule(r,context(r.municipalityCode,r.municipalityName||'Gemeente'),{});assert.ok(Object.values(STATES).includes(e0.state));if([STATES.INSUFFICIENT,STATES.REVIEW].includes(e0.state)){assert.equal(e0.questions.length,0);return}const user=r.applicability.conditions.find(x=>x.source==='user-input');if(user){const e=evaluateRule(r,context(r.municipalityCode,r.municipalityName||'Gemeente'),{[user.id]:'__not_expected__'});assert.equal(e.state,STATES.NOT_APPLICABLE);assert.equal(e.questions.length,0)}}));
if(candidates.length<15)warn('interactieve dekking',`er zijn nu ${candidates.length} interactieve beslisregels; breid de regressieset mee uit zodra meer gemeentelijke regels machineleesbare beslisbomen krijgen`);const geo=regs.filter(r=>r.geographicScopeReview&&r.geographicScopeReview!=='fully-verified').length,noEnd=regs.filter(r=>r.temporal&&!r.temporal.validUntil).length,noApplication=regs.filter(r=>!r.officialApplicationUrl).length;if(noApplication)warn('aanvraagroutes',`${noApplication} regels zonder afzonderlijke aanvraaglink`);if(geo)warn('geografische koppelingen',`${geo} regels nog niet volledig geografisch machineleesbaar`);if(noEnd)warn('einddatums',`${noEnd} regels zonder vaste einddatum; kan correct open-ended zijn`);console.log(`\nRESULTAAT: ${passed} PASS · ${failed} FAIL · ${warnings} WARN`);if(failed)process.exit(1);
